# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.15.0"
  python_check_max: "3.14"

package:
  name: wenmode
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/w/wenmode/wenmode-${{ version }}.tar.gz
    sha256: 06a68774b81d5fffac7b71ee5c3f01ad967eedd11b1ed886a300f8eb46b0b4c0
    target_directory: dist
  - url: https://github.com/lepture/wenmode/archive/refs/tags/${{ version }}.tar.gz
    sha256: f51b52aff1c090e6cda02ae51e6042c20bbf665e1ec60f2a7c79e19b2f96cc4d
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - wenmode = wenmode.cli:main

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: wenmode
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - src/docs/
        - src/pyproject.toml
        - src/README.md
        - src/tests/
    requirements:
      run:
        - mypy
        - pip
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      file: run_test.py

about:
  summary: A fast, composable Markdown parser and renderer toolkit.
  license: BSD-3-Clause
  license_file: dist/LICENSE
  homepage: https://pypi.org/project/wenmode
  documentation: https://wenmode.lepture.com
  repository: https://github.com/lepture/wenmode

extra:
  recipe-maintainers:
    - bollwyvl
